---
# tasks file for docker_ce_centos
# https://docs.docker.com/engine/installation/linux/centos/
- name: check whether docker-ce has already installed
  command: rpm -q docker-ce
  register: result
  changed_when: false
  failed_when: false
- import_tasks: install_docker.yml
  when: result.rc
  static: false
- import_tasks: configure_daemon.yml
  when: docker_centos_daemon_config is defined
  static: false
- name: change the status of the docker daemon
  service:
    name: docker
    state: "{{ docker_centos_state }}"
  when: docker_centos_state is defined
- name: make docker daemon enabled or disabled
  service:
    name: docker
    enabled: "{{ docker_centos_enabled }}"
  when: docker_centos_enabled is defined
- name: add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_centos_users }}"
